### PR TITLE
update code.gitea.io/sdk/gitea to v0.13.1

### PR DESCRIPTION
**Pull request by 6543**
and impruve code

# Be AWARE: go >= 1.13 required

### CODE REVIEW

**Comment by laszlocph** [comment]
Gitea tests fail. But I'm happy to debug it!

Really appreciate keeping us up to date with Gitea!! :+1:

**Comment by 6543** [comment]
I think main issue is fixed with v0.13.1 ...

-> https://gitea.com/gitea/go-sdk/pulls/429

**Comment by 6543** [comment]
@laszlocph can you check, now it should work :)

**Comment by laszlocph** [comment]
I had to extend our mock gitea server with a `/api/v1/version` call, but that's it.

https://github.com/laszlocph/woodpecker/commit/50fc1320feb596824a14ecb46d8a4fcd626d93b5

Thanks for the PR!

**Comment by 6543** [comment]
Nice thanks too 👍 

And yes client check minimum version requirement on client creation

**Comment by 6543** [comment]
@laszlocph I would return 1.12.0 as version!

**Comment by 6543** [comment]
@laszlocph to https://github.com/laszlocph/woodpecker/runs/1187543973

Go >= 1.13 required, client now support context

**Pull request merged**
