### PR TITLE
update code.gitea.io/sdk/gitea to v0.12.0

### PR DESCRIPTION
**Pull request by 6543**
feel free to cherry-pick

https://gitea.com/gitea/go-sdk/src/branch/master/docs/migrate-v0.11-to-v0.12.md

### CODE REVIEW

**Comment by laszlocph** [comment]
Thanks, I will look at it

Do you use this change?

I'm not a Gitea user, so I'd like to rely on your judgement on the Gitea front.

**Comment by 6543** [comment]
I'm a maintainer of gitea and epecialy the sdk ... I just submited this pull because I introduced various breaking changes ... to help

But I dont use woodpecker ... so I sadly cant test it :/ hope this pull still helps

**Comment by 6543** [comment]
only greetings CI failed so the CI itselfe worked ... so I guess the changes should work

by the way tho old code should not worke anymore at all - so I think currently woodpecker do not have any gitea users at the moment

**Comment by laszlocph** [comment]
Gotcha! Really appreciate the PR!

**Pull request merged**
