### PR TITLE
fix: steps of non multi pipline is not display

### PR DESCRIPTION
**Pull request by CrabHo**
### Issue
the steps of non multipipeline aren’t displayed because the div is hidden

### Solution
add a condition to decide the div css class

### CODE REVIEW

**Comment by laszlocph** [comment]
Doh, I missed this bug. Obviously only checked the multipipeline case.

**Comment by laszlocph** [comment]
I have to understand the logic in the PR. Will take a day or two. Thanks for the PR!!

**Comment by CrabHo** [comment]
enhance:
- display status text with pipline and matrix name
- steps div is setup to default open when there is only one process (renderName is false)

**Comment by laszlocph** [comment]
This fixes the problem. I will make a few adjustments after merge to hide the group header if it's a non-multi pipeline build.

**Pull request merged**
