### PR TITLE
Native Kubernetes Support

### PR DESCRIPTION
**Pull request by laszlocph**
#9

### CODE REVIEW

**Comment by laszlocph** [comment]
This feature is parked for now. The code is promising, but not finished up.

**Comment by karolinepauls** [comment]
Hi Laszlo, what remains to be done? How can others help?

**Comment by laszlocph** [comment]
> Hi Laszlo, what remains to be done? How can others help?

That's a good question. By now the master branch diverged quite much, so first, integrating them, then a great deal of testing required.

It was certainly a big bet and I failed to tie the loose ends. Most notably, 
- changes to the yaml format were required to allow for Kubernetes specific settings like resource limits. This was just latched on and I never made a decision. Was contemplating retrofit some some special Docker fields for this. But a unifying model is missing.
- the RWX volume support needed to be opinionated and I never validated my assumptions with any user. So standing full force behind the decision I need some clarity how users want to use it.

In the meantime I started using Woodpecker in a Docker in Docker setup on Kubernetes with success, so I think I should document that first in https://github.com/laszlocph/woodpecker/issues/108

But I could pick the native support up again, but for that I'd love to talk to some users who are interested in this and I can validate some of my assumptions. Make a few more decisions.

**Comment by karolinepauls** [comment]
Maybe perfect is the enemy of good and you can just temporarily declare the unfinished parts as unstable.

Sadly, I ended up configuring a modern-ish Jenkins (gross), but I may end up trying Woodpecker if reintroducing Jenkins results in an uprising of devs.

**Comment by tendant** [comment]
Also would love to see this feature merged, even just basic functionality for Kubernetes support will be great step forward. Others might be able to continue contributing.

**Comment by laszlocph** [comment]
I'm going to salvage the core of this change and merge it.

**Pull request closed without merging**
